services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - n8n_data:/home/node/.n8n
      - ./:/home/node/app
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    ports:
      - 5678:5678
    environment:
      - NODE_ENV=local
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - N8N_PORT=5678
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  n8n_data:
  postgres_data: